### ISSUE TITLE
Memory leak in v0.19.1

### ISSUE THREAD

**Issue by alex2108** [python-lz4/python-lz4#106]
```
import numpy as np
import glob

import lz4.frame

frames=glob.glob('frames_compressed/*.npy.lz4')



for frame in frames:
    print(frame)
    with lz4.frame.open(frame) as f1:
        data=np.load(f1)
        
```

this leads to huge memory usage (due to >50k files in the folder), the same code with lzma works with constant memory usage so I assume there is some leak in lz4

**Comment by jonathanunderwood** [comment]
Thanks for the report and reproducer. I've just cut a new release (0.19.2) which should have fixed this. It'll take a little while to hit PyPi.

I'll close this, but please re-open or file a new issue if you still see problems.
