### ISSUE TITLE
(De)compressor context managers potentially incomplete

### ISSUE THREAD

**Issue by vtermanis** [python-lz4/python-lz4#112]
Hi Jonathan / @jgubmll / @jonathanunderwood, congratulations on frame support & reaching production status!

> We provide context manager classes LZ$FrameCompressor and LZ4FrameDecompressor,

Judging by what's on [top of master](https://github.com/python-lz4/python-lz4/blob/1df99e8a905885666b18701de581c0a26c3e3f78/lz4/frame/__init__.py#L90) I think you might be missing something there since both `__enter__` and `__exit__` methods are empty which is a No-Op and basically means the following two do exactly the same thing:

```python
with lz4.frame.LZ4FrameCompressor() as compressor:
   # do stuff with compressor
   pass
# At this point compressor is still in scope so it's no like
# the context has caused it to be GC'ed.
```
and
```python
compressor = lz4.frame.LZ4FrameCompressor()
# do stuff with compressor
```

You also mention:
> The compression context is created with an appropriate destructor, so no need to del it here

Maybe I'm missing something - where is the appropriate destructor? (I see e.g. no `__del__` method.)

**Comment by jonathanunderwood** [comment]
Thanks! Have fixed on the development branch for `LZ4FrameCompressor` and `LZ4FrameDecompressor`. At some point I had convinced myself that self._context would go out of scope and so be garbage collected, hence the comment. Clearly a thinko.

Will need to review the `LZ4FrameFile` class, but I think that's ok. Too tired to do it now :).

**Comment by jonathanunderwood** [comment]
version 0.23.1 has fixes in for this, so closing. Re-open if I've screwed up :)
