### ISSUE TITLE
Fails to build with Python: nightly

### ISSUE THREAD

**Issue by decibelcooper** [python-lz4/python-lz4#118]
Hey there,

Just so that you are aware, setup.py fails for me with Python: nightly.
https://travis-ci.org/decibelcooper/proio/jobs/341279761#L447

**Comment by jonathanunderwood** [comment]
Thanks for the report. Not sure what's going on there - what is this doing: `pip install --upgrade pytest ./py-proio`? That's where the failure seems to happen - am not convinced that's anything to do with lz4.

**Comment by jonathanunderwood** [comment]
Oh, interesting, reading a bit more carefully I see what's happening. lz4 doesn't have `zip_safe` set, so Python is trying to see if the lz4 package can run from a zip file, or not. And then for some reason it bails. I suppose I could set `zip_safe=False` to prevent this test from happening. But, given it works fine on current Pythons, it seems to me this might be something broken in the Python nightly.

**Comment by decibelcooper** [comment]
Hi @jonathanunderwood,

I had similar thoughts.  Not recommending a change here, just bringing it to your attention.

Cheers!

**Comment by jonathanunderwood** [comment]
Thanks David. I should probably look at adding python nightly builds to
Travis.
