### ISSUE TITLE
Add support for block decompression without a size hint

### ISSUE THREAD

**Issue by llchan** [python-lz4/python-lz4#121]
It would be useful to be able to decompress an lz4 block without knowing the decompressed size up front (i.e. not passed in by the user nor given in a `uint32_t` header). Should be doable by dynamically resizing as it goes. I haven't looked at the lz4 API enough to know if it's possible to realloc and resume, or if it needs to start over, but in either case this function would be a fallback and doesn't need to be super efficient.

It'd also be nice to have an initial size + growth factor exposed, but not strictly necessary.

I should mention that I already have workarounds for my use case so this is not high priority. Just wanted to file it here for consideration.

**Comment by jonathanunderwood** [comment]
Thanks Lawrence, as you know from the fastparquet issue, I had planned to address this. It shouldn't be difficult at all - we already do this for frames where the size isn't present in the frame header.

**Comment by llchan** [comment]
Yep, I know. Just wanted to have an issue here to track and get notifications. Thanks!

**Comment by pravic** [comment]
Same here. Currently I have to catch and parse the "ValueError: Decompressor wrote XXX bytes, but" exception to get the uncompressed size and to call `decompress()` again. I really don't want to do this, though :)

**Comment by frham20** [comment]
Had the same issue as well. Another simple and quick to implement solution could be to have a very very thin wrapper on top of the C API and be able to pass a fixed max buffer size when we know the decompressed size will never be bigger than a certain size. And if it is, we could implement the buffer resizing directly in the client python code as well.

**Comment by pravic** [comment]
Can anyone involved try a #142?

**Comment by jonathanunderwood** [comment]
In the end, since the return code from the LZ4 library block decompression function doesn't differentiate between the output buffer size being too small, I've settled on an approach that allows you to write code like this:

```python
import lz4.block

input = b'0' * 255
c = lz4.block.compress(input, store_size=False)
usize = 20
while True:
    try:
        d = lz4.block.decompress(c, uncompressed_size=usize)
        break
    except lz4.block.LZ4BlockError:
        usize *= 2
assert d == input
```
So, the key changes are:
* `uncompressedd_size`, when greater than zero, is now not strictly checked, but is regarded as an upper bound on the output size.
* A new exception which is raised if the output buffer size is too small to hold the uncompressed data, or if the compressed data is somehow invalid.

This code can be seen on the `block_unknown_size` branch.

**Comment by jonathanunderwood** [comment]
Release 2.1.0, which I've just pushed, includes this.

https://github.com/python-lz4/python-lz4/releases/tag/v2.1.0
