### ISSUE TITLE
Missing `lz4.dumps` in successful install

### ISSUE THREAD

**Issue by rwarren** [python-lz4/python-lz4#125]
After install there is no `lz4.dumps`, or any other method. See below.

```
$ pip install -U lz4
Collecting lz4
Installing collected packages: lz4
Successfully installed lz4-1.1.0
$ python
Python 3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lz4
>>> lz4.dumps
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'lz4' has no attribute 'dumps'
>>> dir(lz4)
['VERSION', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_version', 'library_version_number', 'library_version_string', 'version']
>>> lz4.VERSION
'1.1.0'
>>> lz4.library_version_string()
'1.8.1'
>>> lz4.library_version_number()
10801
>>> 
```

I'm not sure how this can be a legitimate issue, but (and because!) I have tested this on two separate machines (Debian and CentOS), across different python versions (2.7 and 3.6). I have even tried installing older versions of the `lz4` module (going back to 0.23.2). They all have this issue, which makes me think it is on my end, but... not sure what it is across multiple machines??

**Comment by jonathanunderwood** [comment]
Yup, this has long been deprecated I'm afraid.

You should use `lz4.block.decompress()` and `lz4.block.compress()` instead. Or better yet, switch to using the frame format instead.

Please see the docs: http://python-lz4.readthedocs.io/en/stable/

I'll close this issue, as it is expected behaviour. I can only think you were using a really ancient version of the lz4 bindings previously.

**Comment by josephernest** [comment]
I used `lz4` years ago, and I just had the same problem.

@jonathanunderwood what are the advantages/disadvantages of block (`lz4.block.compress()`) vs. frame format?
