### ISSUE TITLE
Gracefully handle old versions of liblz4

### ISSUE THREAD

**Issue by nikitos3000** [python-lz4/python-lz4#136]
Unable to `pip install lz4` if `pkgconfig` python module is already installed and an old version of `liblz4` is present. Details below. 

## Expected Behavior
`pip install lz4` should assume `liblz4_found = False` when `pkgconfig` fails to find the library for any reason. 

## Current Behavior

```shell
$ pip install lz4==2.0.0
    100% |################################| 133kB 53.8MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "tmp/pip-build-pp4a_V/lz4/setup.py", line 22, in <module>
        liblz4_found = pkgconfig.installed('liblz4', LZ4_REQUIRED_VERSION)
      File "tmp/python-lz4/venv/lib/python2.7/site-packages/pkgconfig/pkgconfig.py", line 155, in installed
        raise ValueError(msg)
    ValueError: >= 1.7.5 is not a correct version specifier

```

## Possible Solution

Improve error handling around `pkgconfig.installed()` call in `setup.py`.

```diff
diff --git a/setup.py b/setup.py
index 73a8e2a..2cd413a 100644
--- a/setup.py
+++ b/setup.py
@@ -21,8 +21,9 @@ else:
     try:
         liblz4_found = pkgconfig.installed('liblz4', LZ4_REQUIRED_VERSION)
         py3c_found = pkgconfig.installed('py3c', PY3C_REQUIRED_VERSION)
-    except EnvironmentError:
+    except Exception:
         # Windows, no pkg-config present
+        # or pkgconfig call failed
         pass
```

Maybe both `liblz4_found` and `py3c_found` should be set to `False` too.

## Steps to Reproduce

1. `pip install pkgconfig=1.3.1`
2. `<pkg-manager> install liblz4-dev`
3. edit `liblz4.pc` file, replace version with `Version:  "1.5.r128"`
4. attempt to `pip install lz4==2.0.0`

## Context 

Before ~ 2016 `liblz4` used slightly unconventional versioning schema `...->125->126->127` see
https://github.com/lz4/lz4/blob/r128/lib/liblz4.pc.in

The library was repackaged internally using https://github.com/lz4/lz4/blob/r128/cmake_unofficial/CMakeLists.txt that constructs versions in the format of `X.Y.r###`, e.g. `1.5.r128` in the `liblz4.pc` file:

```
Name: lz4
Description: fast lossless compression algorithm library
URL: http://code.google.com/p/lz4/
Version:  "1.5.r128"
Libs: -L${libdir} -llz4
Cflags: -I${includedir}
```

Python `pkgconfig` module `installed()` [call](https://github.com/matze/pkgconfig/blob/v1.3.1/pkgconfig/pkgconfig.py#L127) fails with `invalid literal for int() with base 10: 'r128'`, because of the assumption it makes about the version format [here](https://github.com/matze/pkgconfig/blob/v1.3.1/pkgconfig/pkgconfig.py#L42)

**Comment by jonathanunderwood** [comment]
Interesting, thanks for the report.

I'd welcome a pull request to fix this. But, it's not good practice to use `except Exception`. I'd prefer to catch the actual exception raised in this case and handle it, preferably printing out a message saying that an old version of the library was found, and that the build will instead use the bundled library.

**Comment by jonathanunderwood** [comment]
Closing since PR #139 fixes this and has now been merged. Thanks again for taking the time to report and fix.
