### ISSUE TITLE
Segfault on frame decompress

### ISSUE THREAD

**Issue by diorcety** [python-lz4/python-lz4#140]
There is an issue in the code for the frame.
Here: https://github.com/python-lz4/python-lz4/blob/master/lz4/frame/_frame.c#L1087
You set to 1 the stableDst even if max_length  is -1 (meaning that PyMem_Realloc can be called) which is incorrect.

**Comment by diorcety** [comment]
Potential fix: https://github.com/diorcety/python-lz4/commit/bcee16884c11212227561bbf7855aa2daa526234
Other Improvements: https://github.com/diorcety/python-lz4/commit/6dbc55a56be379d90a754f59328285e7bcafbaa5

**Comment by jonathanunderwood** [comment]
Thanks for the report. It would be great if you could submit a PR for this,
along with a unit test that fails without the fix and passes with it, so we
don't introduce a regression in the future.

**Comment by jonathanunderwood** [comment]
Having looked carefully at this, I am not convinced you're right. `stableDst` is described [here](https://github.com/lz4/lz4/blob/1466e0b7f29176a1c1792ecc28fa64e29d5aaa69/lib/lz4frame.h#L315) as:

```c
/* pledges that last 64KB decompressed data will remain available unmodified. This optimization skips storage operations in tmp buffers. */
```

Even if `PyMem_Realloc()` is called, any decompressed data is copied across to new the memory region. Further, the current test suite tests exactly the scenario you describe, and I haven't seen any seg faults.

I'd be happy to be wrong though - could you give a recipe that produces the segfault?

**Comment by diorcety** [comment]
I will try. I have crashes. Since this modification, no more crashes.
https://github.com/lz4/lz4/issues/350

**Comment by diorcety** [comment]
https://github.com/lz4/lz4/blob/abb1f70e17c857790d5006012cedf08951a721a0/lib/lz4frame.c#L1731 /* cannot rely on dst data to remain there for next call */

**Comment by diorcety** [comment]
This is linked. if max_length >= 0 the function will no realloc the initial buffer and quit the function. if max_length == -1. The function automatically realloc. We should disable stableDst when max_length == 1

**Comment by jonathanunderwood** [comment]
> We should disable stableDst when max_length == 1

Why? In that case, no realloc occurs. realloc only occurs if max_length == -1. Is that what you meant?

**Comment by diorcety** [comment]
-1. Yes :)

**Comment by jonathanunderwood** [comment]
OK, have merged these changes into the development branch. Many thanks for the report.
