### ISSUE TITLE
LZ4F_getFrameInfo failed with code: ERROR_frameType_unknown

### ISSUE THREAD

**Issue by Nitika123** [python-lz4/python-lz4#143]
I compressed the data using lz4 java library (https://github.com/lz4/lz4-java) and want to decompress it in python using your library. And the compressed data is available in redis cluster. When I execute the following code:

    from rediscluster import StrictRedisCluster
    startup_nodes = [{"host": "my_host", "port": "7002"}]
    rc = StrictRedisCluster(startup_nodes=startup_nodes, decode_responses=False)
    result=rc.hget("key","field")
    from lz4.frame import compress, decompress
    decompress(result)

I am getting the error:"LZ4F_getFrameInfo failed with code: ERROR_frameType_unknown"

What am I doing wrong?

**Comment by jonathanunderwood** [comment]
With only a quick glance at the java binding page, I would guess that the Java bindings don't compress using the frame format, and are probably using the block format.

**Comment by Nitika123** [comment]
Will using lz4.block instead of lz4.frame do the required decoding?

The data that I want to decompress is of the following format:
 
 b'\xfc\x0b\x84\xb0s_w_photogallery\xdc\x00\x15\xc0\xc0\xa13\xc0\x01\x00\xa0\xa820180516\xaa2\x00\xf5\x19images\xdc\x00\x15\xb40.024513947590870666\xa40.29\xa244\xa12F\x00b\xa30.9\xa11\x06\x00b\xc0\xc0\xa3184Q\x00@725\xa9Q\x00Rvideo|\x00\x1515\x00\x10\xc0*\x00 .02\x002\xa2491\x00q407\xa5sto\xa9\x00\xf6\x10\xb30.04410888138287304\xa42.22\xa3858\xa24I\x00\xf0\x14\xa31.1\xa15\xa42.71\xa215\xa40.05\xa11\xa41353\xa820180725'

And when I use lz4.block it gives me the error: "Corrupt input at byte 2"

**Comment by jonathanunderwood** [comment]
It seems the Java bindings don't store the uncompressed size in the compressed string, so you'll need to specify it:

```
>>> import lz4.block as lb
>>> c=b'\xfc\x0b\x84\xb0s_w_photogallery\xdc\x00\x15\xc0\xc0\xa13\xc0\x01\x00\xa0\xa820180516\xaa2\x00\xf5\x19images\xdc\x00\x15\xb40.024513947590870666\xa40.29\xa244\xa12F\x00b\xa30.9\xa11\x06\x00b\xc0\xc0\xa3184Q\x00@725\xa9Q\x00Rvideo|\x00\x1515\x00\x10\xc0*\x00 .02\x002\xa2491\x00q407\xa5sto\xa9\x00\xf6\x10\xb30.04410888138287304\xa42.22\xa3858\xa24I\x00\xf0\x14\xa31.1\xa15\xa42.71\xa215\xa40.05\xa11\xa41353\xa820180725'
>>> lb.decompress(c, uncompressed_size=266)
b'\x84\xb0s_w_photogallery\xdc\x00\x15\xc0\xc0\xa13\xc0\xc0\xc0\xc0\xc0\xc0\xc0\xc0\xc0\xc0\xc0\xc0\xc0\xc0\xc0\xc0\xc0\xa820180516\xaas_w_images\xdc\x00\x15\xb40.024513947590870666\xa40.29\xa244\xa12\xc0\xc0\xc0\xc0\xc0\xc0\xc0\xc0\xc0\xa30.9\xa11\xa30.9\xa11\xc0\xc0\xa3184\xa820180725\xa9s_w_video\xdc\x00\x15\xc0\xc0\xa11\xc0\xc0\xc0\xc0\xc0\xc0\xc0\xc0\xc0\xc0\xc0\xc0\xa31.0\xa11\xc0\xc0\xa249\xa820180407\xa5story\xdc\x00\x15\xb30.04410888138287304\xa42.22\xa3858\xa241\xc0\xc0\xc0\xc0\xc0\xc0\xc0\xc0\xc0\xa31.1\xa15\xa42.71\xa215\xa40.05\xa11\xa41353\xa820180725'
```

**Comment by Nitika123** [comment]
How did you calculate the uncomressed size to be 266?

**Comment by jonathanunderwood** [comment]
I tried to decompress with a much larger size (1024 I think) and looked at the error message. You presumably know the uncompressed size from your application, in any case.

**Comment by jonathanunderwood** [comment]
I'll close this, as I don't think it's an issue as such. Feel free to re-open if you disagree!

**Comment by jonathanunderwood** [comment]
https://github.com/python-lz4/python-lz4/releases/tag/v2.1.0

This release makes it easier to decompress block compressed buffers - you no longer need to provide a precise `uncompressed_size` value. See: http://python-lz4.readthedocs.io/en/stable/lz4.block.html

**Comment by winnie334** [comment]
Leaving a comment here in case it helps someone:
I was trying to LZ4-compress data in Python and decompress it in Java. It kept failing with the message "Error decoding offset 46 of input buffer", even when using `lz4.block` instead of `lz4.frame`. 

In the end I managed to resolve it by changing `lz4.block.compress(payload)` to `lz4.block.compress(payload, store_size=False)`.
