### ISSUE TITLE
pytest-runner a setup requirement ?

### ISSUE THREAD

**Issue by FlingeR** [python-lz4/python-lz4#146]
Hi,
Just wondering...
Why is pytest-runner a setup requirement ?
Shouldn't it be a test requirement ?

```
tests_require = [
    'pytest',
    'pytest-runner',
    'psutil',
],
```
instead of
```
setup_requires=[
        'setuptools_scm',
        'pkgconfig',
        'pytest-runner',
    ],
```

Cheers.
Elias.

**Comment by jonathanunderwood** [comment]
https://docs.pytest.org/en/latest/goodpractices.html

See above. This is needed so that `python setup.py test` is able to invoke `pytest`.

**Comment by FlingeR** [comment]
Clear as water.
It was just a doubt.
Thanks.

**Comment by jonathanunderwood** [comment]
No problem. I have had the same thought as you in the past. :)
