### ISSUE TITLE
Fix depreciated API use in tests/bench.py

### ISSUE THREAD

**Issue by itdaniher** [python-lz4/python-lz4#15]
> lz4.uncompress -> lz4.block.decompress

> lz4.compress -> lz4.block.compress

Otherwise stdout gets a line for each of the 200k loop iterations on each test. Didn't seem worth making a PR over, but annoying enough an upstream fix seemed appropriate.

**Comment by itdaniher** [comment]
For anyone inclined to care, my modified version of tests/bench.py is avail at https://gist.github.com/itdaniher/1586f89c859fb92f772f7f4c8ec17c98.

**Comment by jonathanunderwood** [comment]
PR would be welcome :)
