### ISSUE TITLE
Importing lz4 is very slow

### ISSUE THREAD

**Issue by cgohlke** [python-lz4/python-lz4#154]
On my system (Windows 10 Pro WS, SSD, Python 3.7.1, 64 bit, ~1100 packages installed), importing lz4 is very slow (~3.8 seconds) due to [importing pkg_resources in `__init__.py`](https://github.com/python-lz4/python-lz4/blob/master/lz4/__init__.py#L1), There are [several](https://github.com/pypa/setuptools/issues/926) [issues](https://github.com/pypa/setuptools/issues/510) regarding slow import of pkg_resources.

**Comment by jonathanunderwood** [comment]
Have just cut a new release, 2.1.2 that removes usage of `pkg_resources`. I'll close this, but feel free to re-open if you're still seeing the problem with the new release.
