### ISSUE TITLE
Decompressing fails on buffer compressed in cpp code

### ISSUE THREAD

**Issue by doronAtuar** [python-lz4/python-lz4#166]
Hi,
I don't know if it's a bug in the library or somewhere in my code.
I'll be very grateful for some help

I'm compressing a buffer in cpp using `LZ4_compress_fast` with acceleration=10

When I try to decompress it using python it fails saying
`RuntimeError: LZ4F_getFrameInfo failed with code: ERROR_frameType_unknown`

On the cpp code the decompress works.

I suspect several things:
- missmatch between python's lz4 version and apt liblz4-dev package
- maybe a cpp pack problem since I write it eventually to a file
  (compressing the buff, placing it in Protobuf in a `bytes` field and writing the Protobuf to a file)

Thanks!

additional info:
Ubuntu 16.04
liblz4-dev apt package version 0.0~r131-2ubuntu2
Python 3.6
lz4 python package 2.1.6

**Comment by jonathanunderwood** [comment]
It looks like you're compressing using the block API, and trying to use the frame API to decompress.

So, you need to use the block API for both, or the frame API for both.

Frame API is the recommended of the two, for interoperability.

**Comment by doronAtuar** [comment]
Thanks, now it works!

I changed from `import lz4.frame` to `import lz4.block`
I had to add also `uncompressed_size` to the `decompress` call.

Thank you for the quick response
