### ISSUE TITLE
Trying to get checksum of uncompressed data

### ISSUE THREAD

**Issue by reikdas** [python-lz4/python-lz4#168]
```
>>> import lz4.frame
>>> streamers = b"...." # Wrote this manually
>>> len(lz4.frame.compress(streamers, compression_level=1, content_checksum=True)) - len(lz4.frame.compress(streamers, compression_level=1))
```
returns 4. 
So the length of the checksum is 4. 

Is there a way to get an 8 byte checksum(using xxhash 64)?

**Comment by jonathanunderwood** [comment]
The length of the content checksum is defined by the LZ4 frame specification:

https://github.com/lz4/lz4/blob/master/doc/lz4_Frame_format.md

**Comment by jonathanunderwood** [comment]
You could use the xxhash bindings:

https://pypi.org/project/xxhash/
