### ISSUE TITLE
Compression methods corresponding to the C API

### ISSUE THREAD

**Issue by reikdas** [python-lz4/python-lz4#170]
Am I correct in assuming that the corresponding python method for `LZ4_compress_HC()` is `lz4.block.compress()` with `mode="high_compression"` (and also setting the compression parameter with the required compression level)?
Also, is the corresponding python method for `LZ4_compress_default()` `lz4.block.compress()`?

Also, trying to uncompress bytes compressed by `lz4.block.compress(uncompressed_bytes, mode="high_compression", level=level)` and `lz4.block.compress(uncompressed_bytes)` via `lz4.block.decompress(compressed_bytes)` works, but `lz4.block.decompress(compressed_bytes, uncompressed_size=len(uncompressed_bytes))` does not work. Could you throw some light on this? Is the value of the `uncompressed_size` parameter of `lz4.block.decompress` different from the actual length of the bytes being compressed?

Another way to frame this question would be -
What is the python equivalent of the following C code? 
```
#include <lz4.h>
#include <lz4hc.h>

int foo(int level, int *srcsize, char *src, int *tgtsize, char *tgt) {
    int bar;
    if (level >= 4) {
        bar = LZ4_compress_HC(src, tgt, *srcsize, *tgtsize, level);
    } else {
        bar = LZ4_compress_default(src, tgt, *srcsize, *tgtsize);
    }

    return (int)bar;
}
```

**Comment by jonathanunderwood** [comment]
Your question is answered in the docs:

https://python-lz4.readthedocs.io/en/stable/lz4.block.html#lz4.block.compress

If you don't think that's clear enough, I'd welcome patches to the documentation.
