### ISSUE TITLE
Decompression failed: corrupt input or insufficient space in destination buffer. Error code: 16

### ISSUE THREAD

**Issue by shedance** [python-lz4/python-lz4#178]
import lz4.block as lb

Traceback (most recent call last):
  File "test1.py", line 82, in <module>
    dec = lb.decompress(data,uncompressed_size=208226,return_bytearray=True)
_block.LZ4BlockError: Decompression failed: corrupt input or insufficient space in destination buffer. Error code: 16

get the compressed data from the redis， use the lz4.block to decompress the data , the error occured.

**Comment by shedance** [comment]
the data get from the redis，the data has been compressed by JAVA LZ4，why i read the data from the redis can't be decompressed，the uncompressed_size is right.

**Comment by shedance** [comment]
I resolve this problem·····it's me

**Comment by waqassiddiqi** [comment]
> I resolve this problem·····it's me

I am facing the same problem, how did you solve it?

**Comment by TedSYt** [comment]
+1, same problem, would you like to talk about how you solve it?
