### ISSUE TITLE
0.9 release?

### ISSUE THREAD

**Issue by jleclanche** [python-lz4/python-lz4#18]
Any chance for a 0.9 release? Been waiting for it for a long time, and there havent been any new commits in a month and a half.

**Comment by jonathanunderwood** [comment]
Hi, yes. I've got a few things to commit and will cut a release next weekend. Sorry for the delay - life gets in the way sometimes!

**Comment by jonathanunderwood** [comment]
OK, I've cut a release with what we have so far - frame support is still a WIP.

**Comment by jleclanche** [comment]
Thanks!
