### ISSUE TITLE
Invalid _block.LZ4BlockError: Decompression failed: corrupt input or insufficient space in destination buffer. Error code: 179

### ISSUE THREAD

**Issue by tobgu** [python-lz4/python-lz4#183]
For some shapes of data compressed with https://github.com/pierrec/lz4 this library raises a seemingly incorrect `LZ4BlockerError`. The error indicates that the supplied buffer size is to small to decompress the input. By adding 1 to the supplied expected size the data is decompressed fine though and the size is the expected.

I've attached the smallest compressed example file that I was able to manufacture that fails. There is also a corresponding issue opened here for the Go compressor: https://github.com/pierrec/lz4/issues/58. The investigation done there indicates that the underlying C library manages to uncompress the data fine though which points in the direction of the Python lib.

This is the code used for decompression:
```python
import lz4.block

size = 214
with open(f'test_compressed_{size}.txt', mode='rb') as f:
    # This crashes with _block.LZ4BlockError: Decompression failed: corrupt input or insufficient space in destination buffer. Error code: 179
    result = lz4.block.decompress(f.read(), uncompressed_size=size)

    # This works, the decompressed size is 214 bytes
    # result = lz4.block.decompress(f.read(), uncompressed_size=size+1)
    # print(len(result))   # 214
```
[test_compressed_214.txt](https://github.com/python-lz4/python-lz4/files/3908669/test_compressed_214.txt)

**Comment by jonathanunderwood** [comment]
Thanks for the report.

The following code shows that the go compression library is adding one extra byte to the compressed data:

```python
import lz4.block

with open("test_compressed_214.txt", mode="rb") as f:
    compressed_from_file = f.read()

decompressed_from_file = lz4.block.decompress(
    compressed_from_file, uncompressed_size=215
)

original = b'[{"rqgulitaeas_bitmap":0,"mwsswng_afnce":null,"fm_rxposire_op":null,"lnpmct_abs_diff_pct":null,"pqrstuvwyx_pxtch_eating":null,"fm_wxpssxre_rbs_dwxx_pct":null,"ued_date":"2020-09-15","regglttabns_bitmap_op":0,"dfff_'

print(original == decompressed_from_file)

compressed = lz4.block.compress(original, store_size=False)

print(compressed == compressed_from_file)
print(f"size of compressed original: {len(compressed)}, size of go compressed original: {len(compressed_from_file)}")

decompressed = lz4.block.decompress(compressed, uncompressed_size=214) # this works, note 214.
```

Producing:
```
$ python go_test.py 
True
False
size of compressed original: 189, size of go compressed original: 190
```

So, the reason for the failure is the spurious extra byte of data in the input compressed data you've produced from the go bindings.

**Comment by jonathanunderwood** [comment]
It looks like a fix was applied for the go library, so I'll go ahead and close this. Please feel free to re-open if you think there's still a problem to address here.

**Comment by tobgu** [comment]
Thanks for taking time to look into this! We'll keep digging in the Go library.
