### ISSUE TITLE
Performance lz4.frame.decompress_chunk poor

### ISSUE THREAD

**Issue by bjonen** [python-lz4/python-lz4#184]
I ran into the 2GB limit when compressing with lz4.block and followed the [docs](https://python-lz4.readthedocs.io/en/stable/quickstart.html#working-with-data-in-chunks) to use lz4.frame to be able to compress/decompress via chunks. 

The decompress step seems extremely slow on my machine with test data of ~1GB running python-lz4 version 2.2.1. 

Compared to block (high compression) it runs 7 times slower, compared to lz4framed 15 times slower. 

Output

```
Running lz4 version 2.2.1
Test data 1048.6MB

lz4.block
Compression took 0.2s - size 4.1MB
Deompression took 1.6s
lz4.frame
Compression took 1.1s - size 4.3MB
Deompression took 14.3s
lz4framed
Compression took 5.1s - size 4.3MB
Deompression took 0.8s
```

```
import os
import sys
import time
import lz4
from lz4.block import compress as lz4_compress, decompress as lz4_decompress

print(f'Running lz4 version {lz4.__version__}')
s = 1000 * 1024 *  os.urandom(1024)
print(f'Test data {sys.getsizeof(s)/1.e6:2.1f}MB\n')

print('lz4.block')
lz4_compressHC = lambda _str: lz4_compress(_str, mode='high_compression')
start = time.time()
compressed = lz4_compressHC(s)
end = time.time()
print(f'Compression took {end-start:2.1f}s - size {sys.getsizeof(compressed)/1.e6:2.1f}MB')
start = time.time()
s2 = lz4_decompress(compressed)
end = time.time()
print(f'Deompression took {end-start:2.1f}s')
assert s == s2

print('lz4.frame')
import lz4.frame
start = time.time()
c_context = lz4.frame.create_compression_context()
compressed = lz4.frame.compress_begin(c_context)
compressed += lz4.frame.compress_chunk(c_context, s[:10 * 128 * 1024])
compressed += lz4.frame.compress_chunk(c_context, s[10 * 128 * 1024:])
compressed += lz4.frame.compress_flush(c_context)
end = time.time()
print(f'Compression took {end-start:2.1f}s - size {sys.getsizeof(compressed)/1.e6:2.1f}MB')

start = time.time()
d_context = lz4.frame.create_decompression_context()
d1, b, e = lz4.frame.decompress_chunk(d_context, compressed[:len(compressed)//2])
d2, b, e = lz4.frame.decompress_chunk(d_context, compressed[len(compressed)//2:])
d1 + d2 == s
end = time.time()
print(f'Deompression took {end-start:2.1f}s')

print('lz4framed')
import lz4framed
start = time.time()
compressed = lz4framed.compress(s, level=4)
end = time.time()
print(f'Compression took {end-start:2.1f}s - size {sys.getsizeof(compressed)/1.e6:2.1f}MB')

start = time.time()
s2 = lz4framed.decompress(compressed)
end = time.time()
print(f'Deompression took {end-start:2.1f}s')
assert s == s2
```

**Comment by jonathanunderwood** [comment]
Thanks for this report. I've tracked the problem down to how we're sizing the output buffer. The current strategy, if the uncompressed size is not known is to:

- Assume a compression ratio of 2, and size the output buffer as this number multiplied by the input size
- If decompression isn't complete, increase the output buffer size by 3 times the return value of `LZ4F_decompress` and try again. 

That second step is super dumb, as the return value of `LZ4F_decompress` is just an indication of the number of source bytes which is optimal for the next call, and is the remaining bytes in the current block, plus enough for a block header. So, it's in no way an indication of the compression ratio.

I'll make this a bit smarter.

**Comment by jonathanunderwood** [comment]
I've just cut a new release (3.0.0) which should fix this issue. It'll take a while to publish to PyPi.

Thanks again for the careful report and reproducer, it made it very simple to identify the problem.
