### ISSUE TITLE
lz4.block.compress() missing keyword arguments referenced in docs

### ISSUE THREAD

**Issue by MattTimms** [python-lz4/python-lz4#189]
Despite working as intended, `lz4.block.compress()` in `lz4/block/_block.py` is missing `store_size` and `dict` keyword arguments referenced in docs and its docstrings.

**Comment by jonathanunderwood** [comment]
I suspect you're running a very old version of the package. Please check which version of the Python lz4 package you have installed and report back.

**Comment by jonathanunderwood** [comment]
As you can see, the options are supported and very much there:

https://github.com/python-lz4/python-lz4/blob/master/lz4/block/_block.c#L146

I am going to close this, as I think you must be using an ancient version - certainly if you're installing through Anaconda, whoever maintains those packages haven't updated them in years. If you install using pip you should get the latest version (hint: don't use anaconda).
