### ISSUE TITLE
Tests fail with out of memory error

### ISSUE THREAD

**Issue by grazzolini** [python-lz4/python-lz4#192]
I'm trying to build version 3.0.2 of python-lz4 for the Arch Linux package and the tests fail because the OOM killer is actually kicking in and killing the tests. I have attached the relevant section of the build output. This was on a machine with 128GB of RAM, so I don't think it's an actual hardware issue.

[lz4-error.txt](https://github.com/python-lz4/python-lz4/files/4219028/lz4-error.txt)

**Comment by tSed** [comment]
@grazzolini care to test again with current master, the PR #195 may improve this point.

**Comment by grazzolini** [comment]
@tSed
I have backported the commits on #195 and tried to build, but I'm still getting OOM errors.

[lz4-errors.txt](https://github.com/python-lz4/python-lz4/files/4415403/lz4-errors.txt)
