### ISSUE TITLE
Compressible string not compressed

### ISSUE THREAD

**Issue by saipreetham08** [python-lz4/python-lz4#198]
Hi! 

I just wanted to know if the string "**qabcdefxwvuabcdefghi**" is compressible or not? 
According to my understanding of the algorithm, it is compressible and should yield the result : 
0xb0 0x71 0x61 0x62 0x63 0x64 0x65 0x66 0x78 0x77 0x76 0x75 0x0a 0x00 0x50 0x65 0x66 0x67 0x68 0x69

In the above compressed output, the last 5 bytes are sent as literals and the 'abcd' beginning at index 11 is matched with a previous existing 'abcd' beginning at index 1 and hence compressed. Is there any rule that is being violated in the above compression?

When I try to compress it using the python lz4 module, it does not compress it and sends all the bytes as literals : 
0xf0 0x05 0x71 0x61 0x62 0x63 0x64 0x65 0x66 0x78 0x77 0x76 0x75 0x61 0x62 0x63 0x64 0x65 0x66 0x67 0x68 0x69 

Thanks!

**Comment by jonathanunderwood** [comment]
I am not sure to be honest. This question would be better addressed by the upstream LZ4 project.

**Comment by jonathanunderwood** [comment]
Closing this one.
