### ISSUE TITLE
3.0.2 test failure causes memory error or OOM condition

### ISSUE THREAD

**Issue by dol-sen** [python-lz4/python-lz4#199]
pyhton-lz4-3.0.2
lz4-1.9.2
System has 128GB ram, amd64 arch
>>> psutil.virtual_memory().available
114090119168
>>> lz4.stream.LZ4_MAX_INPUT_SIZE
2113929216
>>> lz4.stream.LZ4_MAX_INPUT_SIZE < 4294967295
True

============================================================================================== FAILURES ==============================================================================================
_____________________________________________________________________________ test_invalid_config_d_4[store_comp_size2] ______________________________________________________________________________

store_comp_size = {'store_comp_size': 4}

    def test_invalid_config_d_4(store_comp_size):
        d_kwargs = {}
        d_kwargs['strategy'] = "double_buffer"
        d_kwargs['buffer_size'] = 1 << (8 * store_comp_size['store_comp_size'])
        d_kwargs.update(store_comp_size)
    
        if store_comp_size['store_comp_size'] >= 4:
    
            if os.environ.get('TRAVIS') is not None:
                pytest.skip('Skipping test on Travis due to insufficient memory')
    
            if sys.maxsize < 0xffffffff:
                pytest.skip('Py_ssize_t too small for this test')
    
            if psutil.virtual_memory().available < 4 * d_kwargs['buffer_size']:
                # The internal LZ4 context will request at least 3 times buffer_size
                # as memory (2 buffer_size for the double-buffer, and 1.x buffer_size
                # for the output buffer), so round up to 4 buffer_size.
                pytest.skip('Insufficient system memory for this test')
    
            # Make sure the page size is larger than what the input bound will be,
            # but still fit in 4 bytes
            d_kwargs['buffer_size'] -= 1
    
        # No failure expected during instanciation/initialization
>       lz4.stream.LZ4StreamDecompressor(**d_kwargs)

d_kwargs   = {'buffer_size': 4294967295, 'store_comp_size': 4, 'strategy': 'double_buffer'}
store_comp_size = {'store_comp_size': 4}

tests/stream/test_stream_1.py:199: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <lz4.stream.LZ4StreamDecompressor object at 0x7f44391cab38>, strategy = 'double_buffer', buffer_size = 4294967295, return_bytearray = 0, store_comp_size = 4, dictionary = ''

    def __init__(self, strategy, buffer_size, return_bytearray=False, store_comp_size=4, dictionary=""):
        """ Instantiates and initializes a LZ4 stream decompression context.
    
            Args:
                strategy (str): Buffer management strategy. Can be: ``double_buffer``.
                buffer_size (int): Size of one buffer of the double-buffer used
                    internally for stream decompression in the case of ``double_buffer``
                    strategy.
    
            Keyword Args:
                return_bytearray (bool): If ``False`` (the default) then the function
                    will return a ``bytes`` object. If ``True``, then the function will
                    return a ``bytearray`` object.
                store_comp_size (int): Specify the size in bytes of the following
                    compressed block. Can be: ``1``, ``2`` or ``4`` (default: ``4``).
                dictionary (str, bytes or buffer-compatible object): If specified,
                    perform decompression using this initial dictionary.
    
            Raises:
                Exceptions occuring during the context initialization.
    
                OverflowError: raised if the ``dictionary`` parameter is too large
                    for the LZ4 context.
                ValueError: raised if some parameters are invalid.
                MemoryError: raised if some internal resources cannot be allocated.
                RuntimeError: raised if some internal resources cannot be initialized.
    
        """
        return_bytearray = 1 if return_bytearray else 0
    
        self._context = _create_context(strategy, "decompress", buffer_size,
                                        return_bytearray=return_bytearray,
                                        store_comp_size=store_comp_size,
>                                       dictionary=dictionary)
E       MemoryError: Could not allocate output buffer

buffer_size = 4294967295
dictionary = ''
return_bytearray = 0
self       = <lz4.stream.LZ4StreamDecompressor object at 0x7f44391cab38>
store_comp_size = 4
strategy   = 'double_buffer'

../lz4-3.0.2-python3_6/lib/lz4/stream/__init__.py:48: MemoryError
====================================================================== 1 failed, 69420 passed, 17360 skipped in 775.03 seconds =======================================================================
 

**Comment by dol-sen** [comment]
After pytest.skip()'ing that test, I got the same error for test_invalid_config_d_5

**Comment by dol-sen** [comment]
tests/stream/test_stream_3.py::test_block_decompress_mem_usage[data0-buffer_size4] PASSED                                                                                                      [ 99%]
tests/stream/test_stream_3.py::test_block_decompress_mem_usage[data0-buffer_size5] 


These 2 tests are also extremely slow, this last one has been ongoing for over 15 minutes.
Should these tests get better buffer size limits?
Note: These tests appear to be single threaded

**Comment by jonathanunderwood** [comment]
Is this still a problem? I suspect it's an issue in pytest.

**Comment by dol-sen** [comment]
I am unable to test this properly for now.  I am away from home with only my laptop which has insufficient memory for those tests and is being skipped by:

if psutil.virtual_memory().available < 4 * d_kwargs['buffer_size']:

I will reach out the the primary package maintainer for this pkg in Gentoo.  Perhaps he can test this properly

**Comment by jonathanunderwood** [comment]
Closing this one. Re-open if you have an update to provide.
