### ISSUE TITLE
lz4 doesn't handle larger file sizes: stream protocol implementation needed

### ISSUE THREAD

**Issue by treeandbrick** [python-lz4/python-lz4#2]
lz4 doesn't handle larger file sizes

```
$ pip list | grep lz4
lz4 (0.8.2)

$ python -c "import lz4; lz4.compress(b'a' * (2 ** 31))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
OverflowError: size does not fit in an int
```

**Comment by jonathanunderwood** [comment]
I am currently working on refactoring the codebase and bringing in the lz4 frame protocol stuff from lz4tools, and will look at dealing with this during that process. Though I have to admit, a good fix hasn't occurred to me yet.

**Comment by darkdragn** [comment]
John, I would like to recommend that this be closed as a non issue. 
    First reason, that overflow error comes about even without lz4. The error is a result of the "b'a' * (2 ** 31). I only realized that as  result of testing it on my own system. It is just a 32 bit system, which could mean this is just reaching the end of my addressing space. 
    Reason 2: The simple fact of that matter is that python-lz4 is only set up to access the basic compress function of the lz4 library, which is not designed to handle large amounts of data. One of the reasons that the frame and stream formats are block based. The usually only handle between 64K and 4MB of data at a time, in other words, per block. Which is the way all large files should be handled.

**Comment by jonathanunderwood** [comment]
I think actually a way to handle this would be to add wrappers for the lz4 stream functions. However, that's really a low priority, and will certainly not happen until well after I've finished restructuring and pulling in the frame format code from @darkdragn . I'll leave this openin the hope that someone finds time to implement the stream functions and submits a pull request :).

**Comment by tstandley** [comment]
+1, I'm getting bit by this too now.
