### ISSUE TITLE
Support for pypy

### ISSUE THREAD

**Issue by dpkp** [python-lz4/python-lz4#20]
The current lz4 library crashes on pypy:

```
→ pypy
Python 2.7.10 (5f8302b8bf9f53056e40426f10c72151564e5b19, Nov 21 2015, 04:15:18)
[PyPy 4.0.1 with GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.1.76)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>> import lz4.frame
>>>> lz4.frame.compress(b'1234')
[1]    23731 segmentation fault  pypy
```

I don't know enough about pypy development right now to debug, so apologies for no PR (because this is a great library!).

**Comment by jonathanunderwood** [comment]
The problem is, PyPy doesn't support extension modules. So this library
would need to be rewritten using the CFFI. Long term that's a good plan.
But while we're still working out the interface details etc, I think
sticking to CPython is the way forward for now.

**Comment by dpkp** [comment]
fwiw, I can't replicate the segfault on PyPy 5.6.0
