### ISSUE TITLE
Installation to local directory breaks

### ISSUE THREAD

**Issue by Battleman** [python-lz4/python-lz4#205]
## Context
Hi,
I'm trying to use a package that uses lz4 (browser_cookie3). My usecase is the following:
* I develop my app locally
* Then I copy everything to a fresh directory
* Install all required packages in the same directory
* Compress everything with zipapp.

This gives me an executable file with all dependencies embedded, that I can distribute easily. This is very similar to what youtube-dl does.

The process has worked so far (tqdm, requests,...), but lz4 seems not to like that. 

## The error/stacktrace
When importing, lz4 throws the following error:
```py
Traceback (most recent call last):
  File "/storage/anaconda3/envs/zoomdl/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/storage/anaconda3/envs/zoomdl/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./testexec/__main__.py", line 1, in <module>
  File "./testexec/lz4/__init__.py", line 14, in <module>
ModuleNotFoundError: No module named 'lz4._version'
```
So apparently it can't find the `lz4/_version.py` file?

## How to reproduce
Here is a minimal set of commands that reproduce the error:

```bash
mkdir test # create target dir
echo "import lz4" > test/__main__.py # create entry point
python3 -m zipapp -p "/usr/bin/env python3" -c -o testexec test/ # "compile" to testexec
./testexec # execute testexec
```

## Meta
Not sure what may help you there... I use:
* Debian 10
* Python 3.7.6
* Anaconda3, within an environment (doesn't work either with system's pip)
* Pip downloads lz4 3.1.0

If there is anything missing, please let me know :)

**Comment by jonathanunderwood** [comment]
Loading of extension modules is not supported by zipapp, and the lz4 package does contain natively compiled extension modules.

See: https://stackoverflow.com/questions/53871993/python-zipapp-with-native-extensions
