### ISSUE TITLE
Wheel support for linux aarch64 [arm64]

### ISSUE THREAD

**Issue by odidev** [python-lz4/python-lz4#207]
Summary
Installing python-lz4 on aarch64 via pip using command "pip3 install python-lz4" tries to build wheel from source code

Problem description
python-lz4 doesn't have wheel for aarch64 on PyPI repository. So, while installing python-lz4 via pip on aarch64, pip builds wheel for same resulting in it takes more time to install python-lz4. Making wheel available for aarch64 will benefit aarch64 users by minimizing python-lz4 installation time.

Expected Output
Pip should be able to download python-lz4 wheel from PyPI repository rather than building it from source code.

@python-lz4-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make python-lz4 wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by jonathanunderwood** [comment]
Please see PR #188 - testing and fixing that would be a good step forward.

**Comment by jonathanunderwood** [comment]
Wheel building for Aarch64 is now in place from 3.1.2 forwards. However, wheel building for Aarch64/Python 3.9 is currently broken.
