### ISSUE TITLE
Further optimize lz4.block.compress based on C reference implementation provided.

### ISSUE THREAD

**Issue by jgutbub** [python-lz4/python-lz4#212]
**Is your feature request related to a problem? Please describe.**
I want to use the lz4.block.compress routine to replace a version I am using based on a C implementation but the python version is not as efficient at compressing the data as the C implementation is.

**Describe the solution you'd like**
Could you consider to reference the C implementation to improve the efficiency of the lz4.block.compress routine you currently have implemented? See below reference for the C implementation (I believe it is derived from https://github.com/lz4/lz4 ):

https://github.com/slimbootloader/slimbootloader/tree/master/BaseTools/Source/C/Lz4Compress

**Describe alternatives you've considered**
I am able to continue to use the C implementation but I would like to transition to using the python version to be more OS-agnostic and avoid the use of any compiled executables for LZ4 compression.

**Additional context**
I did not study the 2 implementations closely so if there might be a way to pass some additional parameters to lz4.block.compress to achieve the same level of compression as the C implementation I would be glad to try any suggestions.

**Comment by jgutbub** [comment]
Some more details, the C implementation I linked to is derived from LZ4 v1.7.4 (e.g. https://github.com/lz4/lz4/releases/tag/v1.7.4).

Is there a specific version of the python lz4 module that I can install via pip that would be compatible with v1.7.4 of LZ4? Or if you have any suggestions on parameters I might be able to specify when calling lz4.block.compress to improve the compression ratio I could try that instead.

**Comment by jgutbub** [comment]
Might have resolved my issue, after checking help(lz4.block) I was able to learn about the mode parameter for the compress routine and when setting mode='high_compression' I am able to achieve similar level of compression as the C implementation.

Closing now but if you have any suggestions please let me know.

**Comment by jonathanunderwood** [comment]
To be super clear: this python package is a wrapper around the C implementation and does not reimplement any of it.
