### ISSUE TITLE
Aarch64 wheel building failing for Python 3.9

### ISSUE THREAD

**Issue by jonathanunderwood** [python-lz4/python-lz4#216]
@ossdev07 - I've added Python 3.9 aarch64 builds to Travis, but the builds seem to fail.Can you have a look and see if you can figure it out?

https://travis-ci.org/github/python-lz4/python-lz4/jobs/754935783

**Comment by jonathanunderwood** [comment]
@odidev any help you can give would also be appreciated.

**Comment by odidev** [comment]
@jonathanunderwood Thanks for uploading the wheels. I checked the logs and I am able to see that there is a timeout which could be due to slow arm64 machine. You can try to re trigger the build once. 
Also travis-ci.org will be shutting down in few weeks with all accounts migrating to travis-ci.com. I would suggest you to migrate python-lz4 to travis-ci.com as well. Once it will be done we can use arm64-graviton for aarch64 build, which is much faster than arm64 machine.

**Comment by jonathanunderwood** [comment]
@odidev thanks - have confirmed that retriggering the job doesn't seem to fix the job, sadly.

**Comment by florence-rolland** [comment]
Hello, do we have an ETA for this issue? I see that https://github.com/python-lz4/python-lz4/issues/208 was closed but the fix is actually blocked by this issue.

**Comment by jonathanunderwood** [comment]
I am afraid I don't have access to arm systems to debug this, and am too time starved to do that via travis jobs, so I am afraid it will remain broken until someone volunteers to fix it.

**Comment by jonathanunderwood** [comment]
I am afraid I don't have access to arm systems to debug this, and am too time starved to do that via travis jobs, so I am hoping a volunteer will step up to look at it.

**Comment by geoffreyblake** [comment]
To add to this, there is no python 3.6 wheel being built for arm64, which causes issues for RHEL8 based installs.

**Comment by geoffreyblake** [comment]
@jonathanunderwood , you can use T4g.micro instances (arm64 based Graviton2) in the free tier at AWS if you need access to an Arm system: https://aws.amazon.com/ec2/instance-types/t4/.

**Comment by jonathanunderwood** [comment]
Thanks @geoffreyblake - thats useful to know. Unfortunately I continue to be quite time starved so won't get to this for a good while, PRs welcome.

**Comment by hrw** [comment]
```
(test) hrw@jagular:python-lz4$ python --version
Python 3.9.2
(test) hrw@jagular:tmp$ git clone https://github.com/python-lz4/python-lz4.git
Cloning into 'python-lz4'...
remote: Enumerating objects: 4789, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 4789 (delta 5), reused 8 (delta 2), pack-reused 4768
Receiving objects: 100% (4789/4789), 1.24 MiB | 2.53 MiB/s, done.
Resolving deltas: 100% (2849/2849), done.
(test) hrw@jagular:tmp$ cd python-lz4/
(test) 11:18 (0s) hrw@jagular:python-lz4$ pip wheel .
Processing /tmp/python-lz4
Building wheels for collected packages: lz4
  Building wheel for lz4 (setup.py) ... done
  Created wheel for lz4: filename=lz4-3.1.4.dev2+g8c8f458-cp39-cp39-linux_aarch64.whl size=1655078 sha256=34c5f653810be28fe446f6ee2701d134e40bc70eb82799d402efcc001d256d27
  Stored in directory: /home/hrw/.cache/pip/wheels/32/f0/1f/c53e1ac5c67ba77514a9fe6c6fe1e7db89f48b08ade7c87a4d
Successfully built lz4
```

Locally (Debian 'bullseye') it builds on AArch64 for Python 3.9

**Comment by jonathanunderwood** [comment]
Aarch64 support will be removed in the next release of python-lz4 as I am having to move away from Travis to Github Actions, and Aarch64 builds just don't work there at present (even if using qemu).

**Comment by hrw** [comment]
Yeah, Arm ecosystem is still behind x86-64 one in too many places.

Sorry to see it go, but I understand your decision.

**Comment by bhumikpatel** [comment]
@jonathanunderwood - We have an initiative (worksonarm) under which we can provide access to Arm server hardware at no cost if that helps. You can register a request here...https://github.com/WorksOnArm/cluster. 

if you need other forms of support for GitHub builds on Arm, we can do that as well, please let me know..Thanks.

**Comment by jonathanunderwood** [comment]
Starting with release 4.3.0, Arm 64 bit wheels are published on pypi.org.
