### ISSUE TITLE
C lib incompatible

### ISSUE THREAD

**Issue by hustbind** [python-lz4/python-lz4#221]
I use lz4 c lib to compress a file,and use python-lz4 to decompress. The decompress can not successs.How can I success the decompress?

**Comment by hustbind** [comment]
throw a exception：_block.LZ4BlockError: Decompression failed: corrupt input or insufficient space in destination buffer. Error code: 21240855

**Comment by jonathanunderwood** [comment]
Without seeing the code you're running, I can't really help.

**Comment by jonathanunderwood** [comment]
Please read the docs:

https://python-lz4.readthedocs.io/en/stable/lz4.block.html#example-usage

In particular, the last example.
