### ISSUE TITLE
ERROR_frameType_unknown

### ISSUE THREAD

**Issue by waqassiddiqi** [python-lz4/python-lz4#229]
I am trying to decompress data compressed using `lz4net` library using following code block:

c# source:
```
var frameType = FrameType.None;
if (content.Length > 1024 * 4) // compress if content spans multiple SSD pages
{
	content = LZ4.LZ4Codec.WrapHC(content);
	frameType = FrameType.Lz4Compressed;
}

var framedContent = new byte[content.Length + 1];
framedContent[0] = frameType;
Buffer.BlockCopy(content, 0, framedContent, 1, content.Length);
```

and the python code to read it is:
```
with open("compressed.msgpk", mode="rb", buffering=0) as f:
    payload = f.read()
    if payload[0] == 1:
        data = lz4.frame.decompress(payload[1:])
```

but it throws:
`RuntimeError: LZ4F_getFrameInfo failed with code: ERROR_frameType_unknown`

**Comment by jonathanunderwood** [comment]
I am completely unfamiliar with the C# bindings you're using, but at a quick glance, that doesn't look like the correct way to create a frame header at all.
