### ISSUE TITLE
Is there a way to check the format of a file?

### ISSUE THREAD

**Issue by Thanh-iT-2001** [python-lz4/python-lz4#230]
i am trying to extract 1 file .bytes but not bt what format is it ?
Can you help me check it?
this is its magic number line

`22 4A 00 EF C6 5F 00 00 28 B5 2F FD 63 E7 55 43 0B C6 5E 3D 13 00 53 0C 2B 58 CC 0B C6 08 42 4C`

**Comment by jonathanunderwood** [comment]
The `file` utility on linux will decode magic bytes for files for you. However, this is a question way out of scope for this github repository. Closing.

**Comment by Thanh-iT-2001** [comment]
please help me identify the standard file format ... Help me

Vào CN, 21 thg 11, 2021 vào lúc 20:51 jonathanunderwood <
***@***.***> đã viết:

**Comment by jonathanunderwood** [comment]
I really don't understand your question. Please try to explain with more detail what you are trying to achieve.

**Comment by Thanh-iT-2001** [comment]
help me.... see if this file is an lz4 compressed file and how can i unzip
it thanks!

Vào Th 6, 26 thg 11, 2021 vào lúc 02:52 jonathanunderwood <
***@***.***> đã viết:
