### ISSUE TITLE
Windows wheel builds are currently broken

### ISSUE THREAD

**Issue by jonathanunderwood** [python-lz4/python-lz4#231]
With the move to github actions for building, testing and publishing to PyPi the Wondows 64 bit builds are breaking on the github action runners. As such the windows builds have been disabled for now. Help fixing these would be gratefully received.

**Comment by elibroftw** [comment]
I was reinstalling my dependencies and lz4 failed. The build message said that "io.h" could not be found. Not sure if that helps at all.

**Comment by elibroftw** [comment]
https://stackoverflow.com/a/50210015/7732434

**Comment by jonathanunderwood** [comment]
> I was reinstalling my dependencies and lz4 failed. The build message said that "io.h" could not be found. Not sure if that helps in any way.

That's not the error I was seeing. What I was seeing is memory allocation failures on 64 bit windows during execution of the tests.

**Comment by cgohlke** [comment]
> That's not the error I was seeing

Do you have a link to an error log? `python-lz4-3.1.10` builds and tests OK locally but peak memory usage during the tests is almost 9 GB on 64-bit Python while on 32-bit it's only ~200 MB...

**Comment by Mik31011** [comment]
I solved with a unofficial binary, maybe isn't the best way, but i really need lz4 https://www.lfd.uci.edu/~gohlke/pythonlibs/#lz4

**Comment by 0lm** [comment]
> I solved with a unofficial binary, maybe isn't the best way, but i really need lz4 https://www.lfd.uci.edu/~gohlke/pythonlibs/#lz4

Hi there. Thanks for your solution. I am currently in the same boat as you. There is something that needs lz4 but it gives me errors when trying "pip install lz4". I am on Windows 10 64bit and using Python 3.9.9 64bit (the official release from official python.org website). Which one of the wheels I need to install in my case? (I am a bit confused about the tags like cp39, cp38, pp38, pypy38, pp73 ... etc. What do they mean and which one is fitting to my version?)

**Comment by martinwang2002** [comment]
> That's not the error I was seeing. What I was seeing is memory allocation failures on 64 bit windows during execution of the tests.

I also find OOM on musllinux builds. `(exited with code -11 (SIGSEGV))`

My builds: https://github.com/martinwang2002/python-lz4/actions/runs/1775567964

**Comment by jonathanunderwood** [comment]
Fixed in 4.0.0
