### ISSUE TITLE
Aarch64 wheels not available on pypi

### ISSUE THREAD

**Issue by tbbharaj** [python-lz4/python-lz4#235]
It looks like aarch64 wheels are no longer available 3.1.9 version onwards on [pypi.org](https://pypi.org/project/lz4/3.1.9/) (https://github.com/python-lz4/python-lz4/commit/0f69a4058d2b3f0bc9ec8ec0315b62153127e40e).
Is it possible to enable them back? 
`pip install lz4` builds from source and fails due to dependencies issues.

Thank you!

**Comment by jonathanunderwood** [comment]
See #216
