### ISSUE TITLE
distutils was deprecated in Python 3.10

### ISSUE THREAD

**Issue by tirkarthi** [python-lz4/python-lz4#236]
https://www.python.org/dev/peps/pep-0632/#migration-advice

https://github.com/python-lz4/python-lz4/blob/8c8f45849bb03ca38374fb2d59c00d6d01694fb9/setup.py#L4

**Comment by jonathanunderwood** [comment]
Setuptools doesn't actually provide/expose equivalent functionality, though. And that migration advice page is useless.

**Comment by jonathanunderwood** [comment]
This [blog post](https://shwina.github.io/custom-compiler-linker-extensions/) provides one way this could be solved.

**Comment by jonathanunderwood** [comment]
Seems the migration path is unclear at present: https://github.com/pypa/setuptools/issues/2806
