### ISSUE TITLE
Wheels for 3.10?

### ISSUE THREAD

**Issue by theintz** [python-lz4/python-lz4#237]
Hi, we are using lz4 through the Sphinx project. We are trying to upgrade to Python 3.10, however, our build is now complaining that there aren't any pre-built lz4 wheels for 3.10:

```
An error occurred while installing lz4==3.1.10; python_version >= '3.1' 
--hash=sha256:d36d0cc0942ef2b30ed69a64ded5e10e64061b2f8e8011c99ffea8a3f8d429c5 
--hash=sha256:dcda8a5fb286251422b271e785b340d551e42f2ffd10953d6aa77a12263d0868 
[many more hashes]
--hash=sha256:48c67beaa312d7f3db66c78cd3d8b4332512489af8ebd9783d4ec735e3337923 
--hash=sha256:6e72e3bc14230db9baf56b05ac15ddc38a9246c414a95ca725af8d5d2226944a!
Will try again.
```

It then proceeds to download the source dist and tries to build a wheel from it, but our build environment does not have a proper build chain configured.

Looking at [the releases page on pypi](https://pypi.org/project/lz4/#files), I can see that `cp39` is the newest supported cpython version. Any plans to publish wheels for 3.10?

**Comment by jonathanunderwood** [comment]
Fixed in 4.0.0
