### ISSUE TITLE
Block size not effecting compression ratio with lz4.frame.compress(data,block_size=xxxx)

### ISSUE THREAD

**Issue by Nathan-L-Cook** [python-lz4/python-lz4#242]
Running 4.0.0
I'm playing with smaller block_size arguments on the lz4.frame.compress() function, but I'm not seeing it have any effect on the compression output.  I'm trying various values like 4096, 8192, with no changes in output.
From the docs: https://python-lz4.readthedocs.io/en/stable/lz4.frame.html

> block_size (int) –
> Sepcifies the maximum blocksize to use. Options:
> 
> lz4.frame.BLOCKSIZE_DEFAULT: the lz4 library default
> lz4.frame.BLOCKSIZE_MAX64KB: 64 kB
> lz4.frame.BLOCKSIZE_MAX256KB: 256 kB
> lz4.frame.BLOCKSIZE_MAX1MB: 1 MB
> lz4.frame.BLOCKSIZE_MAX4MB: 4 MB
> If unspecified, will default to lz4.frame.BLOCKSIZE_DEFAULT which is currently equal to lz4.frame.BLOCKSIZE_MAX64KB.

Is this implying that the minimum block size is 64K?

**Comment by jonathanunderwood** [comment]
You forgot to include sample code.

**Comment by jonathanunderwood** [comment]
Closing this one, as I am not able top reproduce it - if you can provide a reproducer, please re-open.

**Comment by jonathanunderwood** [comment]
> Is this implying that the minimum block size is 64K?

Yes - as defined in the upstream LZ4 library.
