### ISSUE TITLE
4.0.0 macOS wheel has dylib file with broken dependency

### ISSUE THREAD

**Issue by mx-psi** [python-lz4/python-lz4#244]
The macOS wheel for 4.0.0, (`lz4-4.0.0-cp38-cp38-macosx_10_9_x86_64.whl` from [here](https://pypi.org/project/lz4/4.0.0/#files) has a `liblz4.1.9.3.dylib` under the `.dylibs` folder which depends on `/DLC/lz4/.dylibs/liblz4.1.9.3.dylib`. The `/DLC` folder is not present on my Macbook and does not seem to be a standard system path on macOS so the dependency is (very likely) broken.

This does not seem to affect the usage of the wheel; we can run the examples of your website and it works fine. We also can remove the file and basic examples seem to work too. 

### Steps to check

1. Download the macOS wheel for 4.0.0 (any Python version works)
2. Run `wheel unpack lz4-4.0.0-cp38-cp38-macosx_10_9_x86_64.whl`
3. Run `otool -L lz4-4.0.0/lz4/.dylibs/liblz4.1.9.3.dylib`. The output on my machine is:
```
❯ otool -L lz4-4.0.0/lz4/.dylibs/liblz4.1.9.3.dylib
lz4-4.0.0/lz4/.dylibs/liblz4.1.9.3.dylib:
	/DLC/lz4/.dylibs/liblz4.1.9.3.dylib (compatibility version 1.0.0, current version 1.9.3)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.0.0)
```
which shows that it depends on `/DLC/lz4/.dylibs/liblz4.1.9.3.dylib`.
4. Run `otool -L lz4-4.0.0/lz4/_version.cpython-38-darwin.so` or any other `.so` file.
```
❯ otool -L lz4-4.0.0/lz4/_version.cpython-38-darwin.so
lz4-4.0.0/lz4/_version.cpython-38-darwin.so:
	@loader_path/.dylibs/liblz4.1.9.3.dylib (compatibility version 1.0.0, current version 1.9.3)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)
```
As you can see, the `.dylibs` folder dylib is used by `_version.cpython-38-darwin.so`(and similarly for frame and block).

### Additional notes

I thought this could be something that is on the Github Actions macOS runners so I [ran your build actions on a fork](https://github.com/mx-psi/python-lz4/actions/runs/2059825626). As you can see:
- There is no `/DLC` folder on any macOS runner (I added a `Test` step for that) and
- The issue can be reproduced if building on CI

**Comment by KSerrania** [comment]
Some additional information that might be helpful: I tried to build the `lz4-4.0.0-cp38-cp38-macosx_10_14_x86_64.whl` wheel locally (with a simple `python3 -m pip wheel .`). In the resulting wheel, I cannot find the `.dylibs` folder that's present in the official `4.0.0` release:

```
$ ls -la lz4-4.0.0/lz4 
total 44
drwxr-xr-x 7 kylian.serrania staff   224 Mar 29 13:01 .
drwxr-xr-x 4 kylian.serrania staff   128 Mar 29 13:01 ..
-rw-r--r-- 1 kylian.serrania staff   627 Mar 29 13:01 __init__.py
-rw-r--r-- 1 kylian.serrania staff 34112 Mar 29 13:01 _version.cpython-38-darwin.so
drwxr-xr-x 4 kylian.serrania staff   128 Mar 29 13:01 block
drwxr-xr-x 4 kylian.serrania staff   128 Mar 29 13:01 frame
-rw-r--r-- 1 kylian.serrania staff   142 Mar 29 13:01 version.py
```

and the `.so` files in the wheel are linked against another local version of `liblz4` I had on my system:
```
$ otool -L lz4-4.0.0/lz4/_version.cpython-38-darwin.so
lz4-4.0.0/lz4/_version.cpython-38-darwin.so:
        /usr/local/opt/lz4/lib/liblz4.1.dylib (compatibility version 1.0.0, current version 1.9.3)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)
```

**Comment by jonathanunderwood** [comment]
The only thing I can think of is that this happens because of some magic in cibuildwheel. Does this happen with cibuildwheel 2.5.0 as well?

**Comment by mx-psi** [comment]
> The only thing I can think of is that this happens because of some magic in cibuildwheel. Does this happen with cibuildwheel 2.5.0 as well?

Yes, it still happens with cibuildwheel 2.5.0, I just checked this on mx-psi/python-lz4@babd46f0841aabe01df824b0b720dd108efcc82a: 

```
❯ wheel unpack lz4-4.0.1.dev4+gbabd46f-cp38-cp38-macosx_10_9_x86_64.whl
Unpacking to: ./lz4-4.0.1.dev4+gbabd46f...OK

❯ otool -L lz4-4.0.1.dev4+gbabd46f/lz4/.dylibs/liblz4.1.9.3.dylib
lz4-4.0.1.dev4+gbabd46f/lz4/.dylibs/liblz4.1.9.3.dylib:
	/DLC/lz4/.dylibs/liblz4.1.9.3.dylib (compatibility version 1.0.0, current version 1.9.3)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.0.0)
```

**Comment by jonathanunderwood** [comment]
So, digging into this, it seems like this might be expected behaviour from
the `delocate` utility.

Reading back over the comments, it seems like this doesn't cause any actual
problem - is that correct?

**Comment by mx-psi** [comment]
> So, digging into this, it seems like this might be expected behaviour from
the `delocate` utility

Interesting, is that https://github.com/matthew-brett/delocate ?  Do you have a place where we can read more about this?

> Reading back over the comments, it seems like this doesn't cause any actual
problem - is that correct?

We have not done extensive testing but simple examples from the webpage seem to work fine, yes. 

The actual issue we had with this is that our build system verifies all dynamic libraries to ensure that they don't have broken dependencies and fails otherwise. It feels like the correct way to solve this is to eliminate this dead dependency, even if it doesn't seem to cause problems in practice (otherwise I guess we would have to allowlist this somehow?).

**Comment by jonathanunderwood** [comment]
Yes, that is the correct delocate. It is used by cibuildwheel.

I dont see anything about /DLC in the docs,but you can see it mentioned
here:

https://bezier.readthedocs.io/en/0.7.0/native-libraries.html

And also in the source code:

https://github.com/matthew-brett/delocate/blob/master/delocate/delocating.py

**Comment by mx-psi** [comment]
Alright, thanks a lot for the links! I opened an issue on matthew-brett/delocate#150 to discuss this with the delocate maintainers and figure out who should fix this. 

I will close this if it turns out that the link cannot/should not be removed.

**Comment by mx-psi** [comment]
Per the issue above, the issue is on how our build system checks links, since the first item of `otool -L` output is not necessarily a link. Thanks for your help and patience while we figured this out!
