### ISSUE TITLE
Compress and Decompress tar files using LZ4

### ISSUE THREAD

**Issue by arunakalla** [python-lz4/python-lz4#249]
currently I am compressing docker images tar file into Lz4 and Un-taring to load again like this in python.. Basically running linux commands in the python. Wants to use LZ4 compression/decompression (has to be tar, other wise docker won't like it) in native python. **My main goal is super-fast decompression**. Is it even possible with this library?.

******* **Compress**  the docker image*************
```
import os

filename = '~/cloudwatch.tar.lz4'
os.system(f'docker save artifactory.xxx.xxx.com/cloudwatch | lz4 -v > {filename}')
```

******* **Decompress** the tar.lz4 file and load the image*************
```
import os

filename = '~/cloudwatch.tar.lz4'
os.system(f'lz4 -d -v -c {filename}'| docker load')

```

**************************** Current working **compression** code in python for basic tar file ************************

```
from docker import from_env

file_name = '~/cloudwatch.tar.lz4'
client = from_env()
image = client.images.get("artifactory.xxx.xxx.com/cloudwatch")

 with open(file_name, 'wb') as fw:
     for chunk in image.save():
         fw.write(chunk)
```

**************************** Current working **decompression** code in python for basic tar file ************************

```
from docker import from_env

client = from_env()
file_name = '~/cloudwatch.tar.lz4'
 
with open(file_name, 'rb') as fl:    # must be open as bytes
  from_env().images.load(fl)
```

**Comment by jonathanunderwood** [comment]
In your example at no point are you using the python lz4 bindings, so I think you've filed this bug in the wrong place. You're using the lz4 command line tool from [the lz4 project](https://github.com/lz4/lz4), so please seek help there.
