### ISSUE TITLE
compatible problem with lz4-java

### ISSUE THREAD

**Issue by scorpio1858** [python-lz4/python-lz4#251]
I'm having a multi-language problem, I have a python client who compress data and send it to a web server, the web server will use lz4-java (https://github.com/lz4) to do decompress
I wonder if python-lz4 is compatible with the https://github.com/lz4/lz4-java, their apis look so differently

**Comment by jonathanunderwood** [comment]
Really not enough information for me to help you here. Have a look at #232 as a starting point. But also read the provided manual.
