### ISSUE TITLE
Wheel compilation does not work on m1 macs

### ISSUE THREAD

**Issue by BunnyApocalypse** [python-lz4/python-lz4#258]
When trying to install l4z using pip on an m1 mac, the wheel fails to build with this output:

```
      lz4/_version.c:32:10: fatal error: 'Python.h' file not found
      #include <Python.h>
               ^~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
```

Given the failure here with including Python.h, this is indicative of a larger-reaching issue than just lz4, but it is nonetheless a problem that the m1 mac can't compile a common python library by default.

For context, this is on macOS version 12.6.1 with xcode installed and on python 3.9. Pip is also up to date, running `python3 -m pip install wheel setuptools pip --upgrade` also did not fix the issue.

If I am right and this is not an issue with l4z specifically, but instead a wider issue with wheel compilation on the platform, I'd appreciate it if someone could tell me where I should bring this problem next.

**Comment by ifduyue** [comment]
I just tested and it was OK on My macOS 12.6.1 with brew installed python@3.10

```
% ./v/bin/pip install lz4
Collecting lz4
  Downloading lz4-4.0.2.tar.gz (164 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 164.3/164.3 kB 273.0 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: lz4
  Building wheel for lz4 (pyproject.toml) ... done
  Created wheel for lz4: filename=lz4-4.0.2-cp310-cp310-macosx_12_0_arm64.whl size=28203 sha256=3f88a3cc7f7de65a0f666f21f0d00f3f8da1bdc406f67abe28f6fc4a78340a29
  Stored in directory: /Users/duyue/Library/Caches/pip/wheels/2c/a9/71/91bf48a110e61b3619a652359763f9f60dec27257d8f6f34a7
Successfully built lz4
Installing collected packages: lz4
Successfully installed lz4-4.0.2
% ./v/bin/python --version
Python 3.10.8
% ls -al ./v/bin/python
lrwxr-xr-x  1 duyue  wheel  10 Dec 13 21:34 ./v/bin/python -> python3.10
% ls -al ./v/bin/python3.10
lrwxr-xr-x  1 duyue  wheel  44 Dec 13 21:34 ./v/bin/python3.10 -> /opt/homebrew/opt/python@3.10/bin/python3.10
```

**Comment by BunnyApocalypse** [comment]
This is using the version of python installed by xcode. `Python 3.9.6`

**Comment by ifduyue** [comment]
`python3 -m sysconfig` and then figure out at where python headers located, then we can pass it to pip: 

`CFLAGS=-I/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Headers /usr/bin/python3 -m pip install lz` works for me. You can see it's commandlinetools python. I think xcode python can be solved like this way, too. Only you have to figure out the path.

**Comment by jonathanunderwood** [comment]
Aarch64 wheel publishing is firmly at the top of the TODO list. I am hoping to find time to get to that over the Xmas break.

**Comment by jonathanunderwood** [comment]
Starting with release 4.3.0, Arm 64 bit wheels are published on pypi.org.
