### ISSUE TITLE
Allow unknown uncompressed data size in lz4.block.decompress()

### ISSUE THREAD

**Issue by neenar** [python-lz4/python-lz4#26]
In some cases you get lz4 compressed chunk of data without knowing uncompressed data size.

I suggest to allow uncompressed_size (parameter of lz4.block.decompress) accept zero value to indicate that data size is unknown.

**Comment by jonathanunderwood** [comment]
PR would be well received :)

**Comment by jonathanunderwood** [comment]
Actually, that's already implemented in the code. So, I'm a little confused.

**Comment by jonathanunderwood** [comment]
I am going to close this, as I believe what you're asking for already exists. Please re-open and clarify if I have missed something.
