### ISSUE TITLE
Question: How do different levels of compression work internally?

### ISSUE THREAD

**Issue by jackfaubshner** [python-lz4/python-lz4#271]
Hello,

I tried looking in the documentation but was not able to find anything pertaining to it.

Can somebody explain to me how different levels of compression work exactly? Like how does increasing the level decrease the size of the data?

Does it use like a larger window?

Apologies if this is a stupid question, I am a newbie.

Sincerely,
Jack.

**Comment by jmg-duarte** [comment]
It's not a stupid question! 

But this is definitely not the best place to ask it. These are Python bindings for lz4 — this means that the current repository just "re-packages" the original [lz4](https://github.com/lz4/lz4) repo and offers an nice Python interface to it.

This document may help — https://github.com/lz4/lz4/blob/dev/doc/lz4_Frame_format.md — but you may find this video more beginner friendly — https://www.youtube.com/watch?v=goOa3DGezUA

If this solves your issue, don't forget to close it!
