### ISSUE TITLE
enable musllinux builds?

### ISSUE THREAD

**Issue by ixje** [python-lz4/python-lz4#272]
I noticed that the musllinux builds are explicitly skipped
https://github.com/python-lz4/python-lz4/blob/58df0834b57d485f2483bf5ccf1007c313b25557/.github/workflows/build_dist.yml#L61

The [commit](https://github.com/python-lz4/python-lz4/commit/86e5c75915d55f9979fc03efd3d1cc6bb2628366) that disables musllinux builds doesn't have any description on the reason, so I'm wondering if they can be enabled again (assuming they were previously broken)?

**Comment by jonathanunderwood** [comment]
They weren't building and/or passing tests. PRs welcome.

**Comment by jaidenlabelle** [comment]
After testing the musllinux wheels [seem to build fine](https://github.com/jaidenlabelle/python-lz4/actions/runs/12026938511) but fail to pass tests. Is disabling tests for the musllinux builds an acceptable solution?
