### ISSUE TITLE
Wheels for Python 3.13

### ISSUE THREAD

**Issue by henryiii** [python-lz4/python-lz4#287]
Currently wheels for Python 3.13 are missing. This is one of 21 projects in the top 360 Python packages on PyPI to provide 3.12 wheels but not 3.13 wheels. Wheels are safe to build once Python starts releasing RCs.

**Comment by jonathanunderwood** [comment]
Thanks for adding a PR for this. Unfortunately builds aren't currently working, and I am not going to have time to work on this project until december. So, PRs are gratefully received for fixing the build situation, which is a pre-req for getting 3.13 building.

**Comment by henryiii** [comment]
Okay, I can do the artifact action update. Though I'd recommend using dependabot for actions to keep them up to date automatically.
