### ISSUE TITLE
Compile failure on MSVC

### ISSUE THREAD

**Issue by nneonneo** [python-lz4/python-lz4#3]
MS Visual Studio 2008 (which is used for the default python.org Python 2.7 builds) fails to compile lz4 with the following error:

    src/python-lz4.c(131) : error C2143: syntax error : missing ';' before 'type'

This is because MSVC 2008 doesn't permit mixing declarations with code. The fix is simple, and a patch is forthcoming.

**Comment by jonathanunderwood** [comment]
I believe this is already fixed on the refactor branch.

**Comment by nneonneo** [comment]
I'm getting a new compile failure with MSVC with the merged refactor branch:

    lz4/frame/_frame.c(175) : error C2059: syntax error : '{'

The problem here is that MSVC doesn't support compound-literal syntax. As a workaround, you could declare `frameInfo` in a local scope with an initializer and assign it to `prefs->frameInfo` then.
