### ISSUE TITLE
compression failing with 0.9.2

### ISSUE THREAD

**Issue by bmoscon** [python-lz4/python-lz4#35]
Can you help me understand what changed from 0.9.1 to 0.9.2? We compress a lot of output from numpy, eg:

```python
lz4.compressHC(np.packbits(np.ones(len(df), dtype='uint8')))
```

with previous versions of lz4 this was fine, and now in our python 3.5/3.6 environments this fails with the following exception:

```
ValueError: Incorrect type for source object
```

**Comment by jonathanunderwood** [comment]
The change betwee 0.9.1 and 0.9.2 was that now, on Python3 the block compress and decompress functions return a bytearray object rather than bytes. I had thought this wouldn't break API, but this tells me I'm wrong.

I could roll a new release that by default returns a bytes object by default (old behaviour) with a flag to return a bytearray object if specified ?

In general though, I think it would be better to return a bytearray, but I am open to persuasion.

**Comment by jonathanunderwood** [comment]
Oh, wait. No, the change that broke your code is not about what's returned, it's about what you're passing in.

In 0.9.2 we are explicitly expecting source to be either a bytes object or a bytearray object.

**Comment by jonathanunderwood** [comment]
I've just checked a change into the py3_byte_array branch which changes the block functions to first look to see if the source object is a bytearray, and if not, assumes it can be cast to a bytes object. This should revert to giving the old behaviour - can you check.

Overall though, I am not sure how safe this approach is in general. It's unclear to me how, in an extension function, it's possible tosafely deal with all the numpy types - can they all be cast to a bytes object ultimately?

**Comment by jonathanunderwood** [comment]
I have rolled release 0.9.3 with should fix things. But I still question the wisdom of ramming a numpy uint8 array into this function which has historically expected a bytes/string object - I think your code worked more by accident than design.

**Comment by bmoscon** [comment]
A numpy ndarray is basically a byte array but wrapped in the ndarray object. I can convert it to a bytearray very easily (it has a `tobytes` method). Thats fine, but then I get a bytearray back rather than bytes  in python3. Not a huge issue, I can work around in our code.

**Comment by jonathanunderwood** [comment]
OK, great.

If it's helpful, I could revert to returning a bytes object, with a flag (defaulting to False) to request a bytearray is returned. I was on the fence with this change, and in hindsight probably should've left it as it was.

**Comment by bmoscon** [comment]
Ah yes that would help a lot. Converting a numpy array to a bytes object is trivial since thats what it is under the hood, but going from bytearray to bytes incurs an extra copy, so not having to do that would help immensely. I'm even fine with removing the auto cast to bytes/bytearray you added since its trivial to change that before i call.

**Comment by pitrou** [comment]
For information, a Numpy array is not a bytes object under the hood, it has its own allocated memory. When calling `tobytes`, you make a copy of that data. This can be readily seen if you mutate the array afterwards:
```python
>>> a = np.arange(4, dtype='int16')
>>> b = a.tobytes()
>>> b
b'\x00\x00\x01\x00\x02\x00\x03\x00'
>>> a[1] = 42
>>> b
b'\x00\x00\x01\x00\x02\x00\x03\x00'
>>> a.tobytes()
b'\x00\x00*\x00\x02\x00\x03\x00'
```

PR #38 makes it possible to pass Numpy objects directly without calling `tobytes` first, which avoids a copy (and the additional memory consumption of it).
