### ISSUE TITLE
Update bundled lz4 to 1.7.5

### ISSUE THREAD

**Issue by jonathanunderwood** [python-lz4/python-lz4#36]
https://github.com/lz4/lz4/releases

Add support for:

lz4hc : new high compression mode, by @inikep : levels 10-12 compress more (and slower), 12 is highest level

API : lz4frame : LZ4F_compressBound(0) provides upper bound of *flush() and *End() (#290, #280)

**Comment by jonathanunderwood** [comment]
- [x] lz4hc : new high compression mode, by @inikep : levels 10-12 compress more (and slower), 12 is highest level
- [ ] API : lz4frame : LZ4F_compressBound(0) provides upper bound of *flush() and *End() (#290, #280)

**Comment by totaam** [comment]
FYI: 1.8.0 is out:
https://github.com/lz4/lz4/releases/tag/v1.8.0

**Comment by jonathanunderwood** [comment]
Have just cut a new release with 1.8.0 files bundled.
