### ISSUE TITLE
PyCapsule_New calls have no destructor - memory leak

### ISSUE THREAD

**Issue by nneonneo** [python-lz4/python-lz4#5]
None of the calls to `PyCapsule_New` are passing in a destructor. The result is that the various heap-allocated chunks inside these capsules will eventually leak.

For example, calling `lz4.frame.makePrefs()` in a loop will eventually consume all memory even if the result is not bound to a variable.

**Comment by jonathanunderwood** [comment]
Yup.. I've basically pulled that code over from the lz4tools project, and have been squashing memory problems in the process (lots associated with returning Py_NONE, for example), and had on the list to tackle this, as well as build a test suite for the frame stuff.

But actually, I'm in two minds as to whether using Py_Capsule at all for this is the right design, particularly for the prefs. I think it may be better to instead pass in the prefs explicitly on each call to compress and friends. But, the downside of that is that it relies on the user ensuring consistent preferences are used across each call to compress.

Perhaps I'll expand the API to allow both ways of working... thoughts welcome :)

**Comment by jonathanunderwood** [comment]
OK, this should now be fixed in master. I've added destructors for now. I'll give more thought to changing the API in the near future though.

I'll close this, but feel free to add any more comments, or re-open if you think there's anything unaddressed - so far I haven't had any time to test the frame module - next job is to add a test suite for it.

**Comment by nneonneo** [comment]
Hmm, so I didn't realize that you had explicit destructor functions (`freeCompContext` and friends). Perhaps with the new destructors, the explicit free wrappers should be removed, so that you don't get a double free from people inadvertently calling a free function and then letting the variable expire.

**Comment by jonathanunderwood** [comment]
Yeah... had thought of removing them... but I want the lz4tools project to be able to work with this library without change initially. So, I plan to leave those functions, at least for now, but mark them as deprecated and dangerous in the docs. Or maybe leave them as stubs that do nothing. Not sure yet.

**Comment by jonathanunderwood** [comment]
Re-opening this to remind me there's still a decision to be made.

**Comment by jonathanunderwood** [comment]
Closing now. Decided not to put a premium on lz4tools compatibility.
