### ISSUE TITLE
decompress() shouldn't expect the data to start with the size

### ISSUE THREAD

**Issue by jleclanche** [python-lz4/python-lz4#6]
Unity3d uses lz4 to compress blocks of data. The size is stored separately. In order to use this library to decompress the blocks in question, a buffer has to be recreated which is unnecessarily slow.

Could you add a way to specify the data size through an argument?

**Comment by jonathanunderwood** [comment]
It's possible, I suppose to extend the block capability to accommodate this. But, it would actually be better to instead use the lz4 frame spec. I'm in the process of adding frame support to this library (see master branch).

**Comment by jonathanunderwood** [comment]
Capability to not store/require the uncompressed data size in the blockwas added in commit 75d3fe34d951e0306fd07a6496fcd6732876dc2b

**Comment by jleclanche** [comment]
@jonathanunderwood thank you. I hope to see a new release soon, the current pypi master is really outdated

**Comment by jonathanunderwood** [comment]
I have done all the coding I plan to do now for the next release. Just a few documentation pieces needed, and I'll release something.
