### ISSUE TITLE
LZ4_VERSION mismatch

### ISSUE THREAD

**Issue by tclh123** [python-lz4/python-lz4#61]
1. According to https://github.com/python-lz4/python-lz4/commit/1a13ecc9e30341254a16cad908a89971d6c871f6, LZ4_VERSION hardcoded in setup.py should be updated, or it will mislead people.
2. The setup.py should be improved. If the version of liblz4 found is lower than requirements, bundled LZ4 library should be used.

**Comment by jonathanunderwood** [comment]
Thanks for the report.

> According to 1a13ecc, LZ4_VERSION hardcoded in setup.py should be updated, or it will mislead people.

Good point - I forgot to update LZ4VERSION. However, the plan for that is for it to be removed, as it's inherently fragile. Instead, the `lz4.lz4version()` function should be used instead, which calls `LZ4_versionNumber ()` to get the version number directly from the library. I might add an option to have that return the version as a semver in the future.

> The setup.py should be improved. If the version of liblz4 found is lower than requirements, bundled LZ4 library should be used.

Hm. Well, I am not sure that's necessarily the desirable outcome for some users. For example, a distro packager will want to use the system lz4 library irrespective of whether the bundled one is newer. Perhaps what is needed is an explicit option adding to setup.py e.g. `--use-system-lz4`. Unless you have a better suggestion?

**Comment by tclh123** [comment]
Hello @jonathanunderwood 

> For example, a distro packager will want to use the system lz4 library irrespective of whether the bundled one is newer.

It's not about whether the bundled one is newer, it's about whether the version of lz4 library meets the requirements of python-lz4.

python-lz4 should declare the minimum required version of the lz4 library. e.g. python-lz4 v0.12.0 need lz4 1.8.0

I think if the system lz4 lower than the requirements, we can use the bundled one and echo some warnings.

> Perhaps what is needed is an explicit option adding to setup.py e.g. --use-system-lz4.

Maybe it'll be helpful to people who use `python setup.py`, but not who use `pip`. Because 
 it seems there's no way to pass the option in `pip install xxx` or `pip install -r xxx` https://pip.pypa.io/en/stable/reference/pip_install/#requirements-file-format .

**Comment by jonathanunderwood** [comment]
OK, thanks, so that's a slightly different ask. I have tried, in general, to support LZ4 libraries going back quite a long way. However, I agree, a minimum LZ4 version check would be useful.

For now, I have cut a new release (0.13.0) which remove LZ4_VERSION. I'll leave this issue open until I've added logic for defining and checking a minimum lz4 version.

**Comment by jonathanunderwood** [comment]
Version 0.14.0 specifies a minimum LZ4 library version of 1.7.5, and builds against the bundled version if that's not mer.
