### ISSUE TITLE
It would be nice for windows users if pre-compiled Wheels were published

### ISSUE THREAD

**Issue by jdb-vsn** [python-lz4/python-lz4#7]
Many Windows users don't have compilers installed, and if they do have some C++ compiler it is likely NOT to be the correct one for building C modules for their installed Python version.

Pre-built wheels would make this much easier for Windows users.

**Comment by jonathanunderwood** [comment]
Good point, will do so for the next release.

**Comment by jonathanunderwood** [comment]
Hm. I don't have access to Windows machines, and it seems like PyPi doesn't offer a wheel build service? Is there any standard way of generating windows and osx wheels without access to such platforms?

**Comment by jonathanunderwood** [comment]
I've begun trying to integrate appveyor builds, which should give us this functionality. I'm totally new to appveyor, so if you have any experience, help is definitely welcome!

**Comment by jonathanunderwood** [comment]
Closing this. I have appveyor builds working. If with little work I can use that to publish wheels, I will. If i find it's taking too much time, I won't bother, unless someone else steps up to the plate to help. I find it hard to care about Windows.

**Comment by jonathanunderwood** [comment]
Re-opening this for tracking, as it would be nice to have, and isn't much more extra work at this point.

**Comment by jonathanunderwood** [comment]
From 0.16.4 onwards windows wheels are being pushed automatically from AppVeyor to PyPi. Testing would be appreciated. 

Closing this. Please open a new issue if there are any problems with the published wheels.
