### ISSUE TITLE
memory leak in lz4.frame.decompress

### ISSUE THREAD

**Issue by bt-wil** [python-lz4/python-lz4#96]
```
> python --version
Python 3.6.3
> pip freeze | fgrep lz4
lz4==0.18.1
```

I'm encountering an issue where when I run the script below, I can see the memory increasing.  At the end, the memory using is ~4GB looking at `htop`.

```
import lz4.frame
import tracemalloc
import time


tracemalloc.start()

input_data = 'a' * 1024 * 1024
compressed = lz4.frame.compress(input_data.encode('utf-8'))

prev_snapshot = None

for i in range(5000):
    decompressed = lz4.frame.decompress(compressed)

    if i % 100 == 0:
        snapshot = tracemalloc.take_snapshot()
        top_stats = snapshot.statistics('lineno')

        print(" top: {}".format(top_stats[0]))

        if prev_snapshot:
            top_stats = snapshot.compare_to(prev_snapshot, 'lineno')
            print("diff: {}".format(top_stats[0]))

        print()
        time.sleep(0.5)

        prev_snapshot = snapshot

print('done')
time.sleep(10)
```

```
 top: mem-look.py:14: size=101 MiB, count=101, average=1024 KiB
diff: mem-look.py:14: size=101 MiB (+100 MiB), count=101 (+100), average=1024 KiB
...
 top: mem-look.py:14: size=4901 MiB, count=4901, average=1024 KiB
diff: mem-look.py:14: size=4901 MiB (+100 MiB), count=4901 (+100), average=1024 KiB
```

**Comment by jonathanunderwood** [comment]
Interesting, thanks for the report. Will investigate.

**Comment by jgubmll** [comment]
My initial, untested, guess is that we're incrementing the ref count on the return value one time too many, so  it never gets free'd. In __decompress:

```
py_destination = PyBytes_FromStringAndSize (destination, (Py_ssize_t) destination_written);
```
means py_destination has a ref count of 1. Then, doing:

```
return Py_BuildValue ("O", py_destination);
```

increases the ref count by 1 again. As I say, untested, but I think that's what's going on. We should just return py_destination - the call to Py_BuildValue is unneeded there.

**Comment by jonathanunderwood** [comment]
My initial, untested, guess is that we're incrementing the ref count on the return value one time too many, so  it never gets free'd. In __decompress:

```
py_destination = PyBytes_FromStringAndSize (destination, (Py_ssize_t) destination_written);
```
means py_destination has a ref count of 1. Then, doing:

```
return Py_BuildValue ("O", py_destination);
```

increases the ref count by 1 again. As I say, untested, but I think that's what's going on. We should just return py_destination - the call to Py_BuildValue is unneeded there.

**Comment by jonathanunderwood** [comment]
Yep, confirmed that's the cause. Will role a new release shortly to fix this.

**Comment by jonathanunderwood** [comment]
I have just cut a new release (0.18.2) which fixes this issue, and also adds a test for memory usage in this function based on your reproducer. Many thanks for the super helpful report and reproducer.
